### ISSUE TITLE
Add ability to change dimensions of CPW of the claw for the TransmonCross

### ISSUE THREAD

**Issue by andrekuo** [qiskit-community/qiskit-metal#946]
Please be as descriptive as possible, including: what is expected, why is this feature needed, what is the objective, etc.

### What is the feature being requested?
The ability to add custom dimensions for the CPW leading out of the claw on a transmon cross

### What are use cases for this feature?
All kinds of qubit design

**Comment by zlatko-minev** [comment]
Thanks Sent from my iPhoneOn Jun 19, 2023, at 8:26 PM, Andre Kuo ***@***.***> wrote:﻿
Closed #946 as completed.
