### ISSUE TITLE
"environemt.yml" is spelled wrong in the Qiskit Metal Installation docs

### ISSUE THREAD

**Issue by andrekuo** [qiskit-community/qiskit-metal#948]
### What is the documentation modification?
On the Metal Installation guide, `environment.yml` is spelled as `environemt.yml`, as shown:
![image](https://github.com/Qiskit/qiskit-metal/assets/50998428/1bb6e04e-53e8-4d81-bc81-4a282b998151)

Apologies if this is a frivolous issue

**Comment by zlatko-minev** [comment]
Thank you!
