### ISSUE TITLE
Bug documentation website render

### ISSUE THREAD

**Issue by soosub** [qiskit-community/qiskit-metal#966]
### What is the documentation modification?
There seems to be an issue when deploying the documentation website for Qiskit Metal. See screenshots below or e.g. [the example on resonator meandering](https://qiskit.org/documentation/metal/circuit-examples/B.Resonators/11-Resonator_Meander.html). As a quick fix, checking out the notebooks directly on github is fine but it would be nice to view them normally on the website too.

Cheers!

![image](https://github.com/qiskit-community/qiskit-metal/assets/44366402/4b2f161d-cc12-48d6-93a9-cf2846ee17ee)
![image](https://github.com/qiskit-community/qiskit-metal/assets/44366402/6bdae4b8-31b5-48d5-9e04-4deb9cbb39c4)

**Comment by q-inho** [comment]
I think this problem also has been solved after this [PR](https://github.com/qiskit-community/qiskit-metal/pull/975) merged.

**Comment by zlatko-minev** [comment]
Thanks!

**Comment by soosub** [comment]
Great, many thanks @q-inho !
