### ISSUE TITLE
Display issue in the documentation

### ISSUE THREAD

**Issue by maxhant** [qiskit-community/qiskit-metal#978]
### Information

- **Qiskit Metal version**: 0.1.5
- **Python version**: NA
- **Operating system**: Windows on chrome and edge 

### What is the current behavior?

I have a gray square that prevents me from looking/selecting the online documentation. 

![image](https://github.com/qiskit-community/qiskit-metal/assets/52139175/e762e46f-54e7-4074-8cd3-b2b7395f9014)

### Steps to reproduce the problem

Go on this [link](https://qiskit.org/ecosystem/metal/circuit-examples/index.html).

### What is the expected behavior?

Gray square that blocks the page.

### Suggested solutions

No idea.

**Comment by q-inho** [comment]
I think this problem has been solved after this [PR](https://github.com/qiskit-community/qiskit-metal/pull/975) merged.
