### ISSUE TITLE
Set up GitHub Pages and update the About section

### ISSUE THREAD

**Issue by arnaucasau** [qiskit-community/qiskit-metal#984]
### Instructions 
The project now has the documentation deployed in a branch called [gh-pages](https://github.com/qiskit-community/qiskit-metal/tree/gh-pages), but we need to set up the repo to use GitHub Pages by following the next 5 steps. Once the GitHub Pages is set up please update the repo's About section to display the new link.

1. Navigate to your site's repository
2. Click `Settings`
3. Go to `Pages`
4. Select `Deploy from a branch`, under the `Source` section on `Build and deployment`
5. Select the `gh-pages` branch and the `/ (root)` folder in the `Branch` section on `Build and deployment`

![GitHubPages-example](https://github.com/Qiskit/ecosystem/assets/47946624/520f4f0c-905a-4a4f-b918-a580a953e80d)

The default URL where you can find your site is https://qiskit-community.github.io/qiskit-metal

For further information, you can see the [GitHub Pages Quickstart](https://docs.github.com/en/pages/quickstart#creating-your-website) and https://github.com/Qiskit/ecosystem/issues/578.

**Comment by zlatko-minev** [comment]
Thank you! Ok, so i just did this, what's next 
<img width="1015" alt="image" src="https://github.com/qiskit-community/qiskit-metal/assets/15937254/6e454860-176a-4043-9083-b86265a4c45c">

**Comment by zlatko-minev** [comment]
We will want to merge this branch in the main sometime?

**Comment by arnaucasau** [comment]
Thank you @zlatko-minev! The page is now working at https://qiskit-community.github.io/qiskit-metal :tada: 

No need to merge the branch, the `gh-pages` branch contains the docs built, and thanks to the new workflow it will be updated at each push to the main, similar to how we deployed to qiskit.org before :)

The only thing left in the issue is to change the link in the About section of the repo to show the new one.

![Captura desde 2024-02-07 15-06-03](https://github.com/qiskit-community/qiskit-metal/assets/47946624/79e9a279-b004-4376-8a39-059d6063e615)

P.S. If someday you want to deploy the docs from a stable version, the deployment changes introduced in this [commit](https://github.com/qiskit-community/qiskit-metal/commit/5fd9379e22dacdf4b7bf7d67eb327b969c31ed13) will need to be backported

**Comment by zlatko-minev** [comment]
Awesome, thank you! Updated!

**Comment by arnaucasau** [comment]
Thank you!!
